import Head from "next/head";
import Modal from "../components/Modal";
import Banner from "../containers/Banner";
import Projects from "../containers/Projects";

export default function Home() {
   return (
      <div>
         <Head>
            <title>Fratila Catalin - Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <div>
            <Banner />
            <div className="modals">
               <Modal src="/Images/about.png" title="About" />
               <Modal src="/Images/contact.png" title="Contact" />
            </div>
            <Projects />
         </div>
      </div>
   );
}
